"""TS-4 — graph-corpus regression test (REQ-GRA-009).

Byte-compares the graph built for tests/graph_fixtures/{python,go}/ against
committed golden files. Fails CI on any upstream graphifyy schema drift or
regression in vulnhunter_fix.graph.build normalization.

Under grep-fallback (graphify not installed), the golden was generated by
the same fallback path, so the comparison remains stable across CI runs.
Once graphify is installed in CI, the goldens must be regenerated once and
committed; that PR will be the schema-lock point per REQ-GRA-009.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURES = REPO_ROOT / "tests" / "graph_fixtures"


def _normalize(doc_dict: dict) -> dict:
    """Strip fields that are inherently non-deterministic across builds."""
    d = dict(doc_dict)
    d["generated_at"] = ""
    d["content_hash"] = ""
    root_dir = d.get("root_dir", "")
    if root_dir:
        # Normalize to a repo-relative form so absolute paths don't leak in.
        try:
            rel = Path(root_dir).resolve().relative_to(REPO_ROOT)
            d["root_dir"] = str(rel)
        except (OSError, ValueError):
            d["root_dir"] = ""
    return d


@pytest.mark.parametrize("lang", ["python", "go"])
def test_graph_fixture_matches_golden(lang):
    import sys

    sys.path.insert(0, str(REPO_ROOT))
    from vulnhunter_fix.graph.build import build_graph

    fixture_dir = FIXTURES / lang
    golden_path = fixture_dir / "golden.graph.json"
    assert golden_path.exists(), f"missing golden at {golden_path}"

    doc = build_graph(fixture_dir)
    actual = _normalize(doc.to_dict())
    expected = json.loads(golden_path.read_text(encoding="utf-8"))

    for field in ("schema_version",):
        assert actual[field] == expected[field], (
            f"drift in {field}: expected {expected[field]!r}, got {actual[field]!r}"
        )

    if actual["backend"] != expected["backend"]:
        pytest.skip(
            f"golden was generated under backend={expected['backend']!r} but this "
            f"run produced backend={actual['backend']!r}. Regenerate the golden in "
            f"the intended env with: `python3 -c \"import json, sys; sys.path.insert(0,'.'); "
            f"from vulnhunter_fix.graph.build import build_graph; "
            f"d = build_graph('tests/graph_fixtures/{lang}').to_dict(); "
            f"d['generated_at']=''; d['content_hash']=''; d['root_dir']='tests/graph_fixtures/{lang}'; "
            f"json.dump(d, open('tests/graph_fixtures/{lang}/golden.graph.json','w'), "
            f'indent=2, sort_keys=True)"`'
        )

    actual_nodes = set(actual["nodes"].keys())
    expected_nodes = set(expected["nodes"].keys())
    assert actual_nodes == expected_nodes, (
        f"node id drift for {lang}:\n"
        f"  missing: {sorted(expected_nodes - actual_nodes)}\n"
        f"  extra:   {sorted(actual_nodes - expected_nodes)}"
    )

    for nid, expected_node in expected["nodes"].items():
        actual_node = actual["nodes"][nid]
        for key in ("kind", "name", "file", "qualified_name", "language"):
            assert actual_node.get(key) == expected_node.get(key), (
                f"node {nid} field {key} drifted: "
                f"expected {expected_node.get(key)!r}, got {actual_node.get(key)!r}"
            )
